const tempData = [
  {
    title: "Guardians of the Galaxy Vol. 2",
    year: 2017,
    director: "James Gunn",
    duration: "2h 16min",
    genre: ["Action", "Adventure", "Comedy"],
    rate: 7.7,
    poster: "https://m.media-amazon.com/images/I/A11Agdd1EQL.jpg",
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    year: 1977,
    director: "George Lucas",
    duration: "2h 1min",
    genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    rate: 8.7,
    poster: "https://m.media-amazon.com/images/I/81P3lDJbjCL.jpg",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    director: "Peter Jackson",
    duration: "2h 58min",
    genre: ["Action", "Adventure", "Drama", "Fantasy"],
    rate: 8.8,
    poster: "https://m.media-amazon.com/images/I/81EBp0vOZZL.jpg",
  },
  {
    title: "Casablanca",
    year: 1942,
    director: "Michael Curtiz",
    duration: "1h 42min",
    genre: ["Drama", "Romance", "War"],
    rate: 8.5,
    poster: "https://m.media-amazon.com/images/I/712GZT4eFwL._AC_UF894,1000_QL80_.jpg",
  },
  {
    title: "2001: a Space Odyssey",
    year: 1968,
    director: "Stanley Kubrick",
    duration: "2h 29min",
    genre: ["Adventure", "Sci-Fi"],
    rate: 8.3,
    poster: "https://m.media-amazon.com/images/I/91BXn+piMoL.jpg",
  },
  {
    title: "Avatar",
    year: 2009,
    director: "James Cameron",
    duration: "2h 42min",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rate: 7.9,
    poster: "https://m.media-amazon.com/images/I/81D1F9g+x0L.jpg",
  },
  {
    title: "Jurassic Park",
    year: 1993,
    director: "Steven Spielberg",
    duration: "2h 7min",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rate: 8.2,
    poster: "https://m.media-amazon.com/images/I/61eYnvs0zaL.jpg",
  },
  {
    title: "Léon: The Professional",
    year: 1994,
    director: "Luc Besson",
    duration: "1h 50min",
    genre: ["Action", "Crime", "Drama"],
    rate: 8.5,
    poster: "https://m.media-amazon.com/images/I/61P-HNp5QsL._AC_UF894,1000_QL80_.jpg",
  },
  {
    title: "The Lion King",
    year: 1994,
    director: "Roger Allers - Rob Minkoff",
    duration: "1h 28min",
    genre: ["Animation", "Adventure", "Drama"],
    rate: 8.5,
    poster: "https://m.media-amazon.com/images/I/91Yl69HNKBL.jpg",
  },
  {
    title: "10 Things I Hate About You",
    year: 1999,
    director: "Gil Junger",
    duration: "1h 37min",
    genre: ["Romance", "Comedy", "Drama"],
    rate: 7.3,
    poster: "https://m.media-amazon.com/images/I/71dgB-Pj61S.jpg",
  },
];
